"""Generate an equivalent k6 script, for users who already run k6 (or Grafana Cloud k6) themselves.

  python -m launchproof.load.k6gen --url https://site --paths / /pricing > launchproof.k6.js
  k6 run launchproof.k6.js
"""
from __future__ import annotations

import argparse
import json

TEMPLATE = """import http from 'k6/http';
import {{ sleep }} from 'k6';

// Generated by Launchproof. Same ramp, caps and break point rules as the hosted test.
const BASE = {base};
const PATHS = {paths};
const RUN = {run};

export const options = {{
  scenarios: {{
    ramp: {{
      executor: 'ramping-vus',
      startVUs: 0,
      stages: {stages},
      gracefulRampDown: '5s',
    }},
  }},
  thresholds: {{
    // Break point rules: abort as soon as the site is clearly failing.
    http_req_failed: [{{ threshold: 'rate<0.05', abortOnFail: true, delayAbortEval: '10s' }}],
    http_req_duration: [{{ threshold: 'p(95)<5000', abortOnFail: true, delayAbortEval: '10s' }}],
  }},
  userAgent: `LaunchproofLoadTest/1.0 (+https://launchproof.xyz/bot; run=${{RUN}})`,
}};

export default function () {{
  const path = PATHS[Math.floor(Math.random() * PATHS.length)];
  http.get(BASE + path, {{ headers: {{ 'X-Launchproof-Run': RUN }} }});
  sleep(1 + Math.random() * 2);
}}
"""


def generate(url: str, paths: list[str], stages: list[int], stage_seconds: int = 30, run_id: str = "k6") -> str:
    k6_stages = [{"duration": f"{stage_seconds}s", "target": min(s, 1000)} for s in stages]
    return TEMPLATE.format(base=json.dumps(url.rstrip("/")), paths=json.dumps(paths),
                           run=json.dumps(run_id), stages=json.dumps(k6_stages))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", required=True)
    ap.add_argument("--paths", nargs="+", default=["/"])
    ap.add_argument("--stages", default="10,25,50,100,200,400,800")
    ap.add_argument("--stage-seconds", type=int, default=30)
    a = ap.parse_args()
    print(generate(a.url, a.paths, [int(x) for x in a.stages.split(",")], a.stage_seconds))
